//! Headless browser rendering for SPA (Vue/React/Angular) sites.
//!
//! Traditional crawling fetches raw HTML and parses `<a href>` links.
//! SPA sites ship a bare `<div id="app">` shell — the actual content is
//! generated by JavaScript at runtime. This module drives a headless
//! Chromium to execute that JS, capture the fully-rendered DOM, and
//! intercept typed static network requests for offline mirroring.

use std::collections::HashSet;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use anyhow::{anyhow, Result};
use chromiumoxide::browser::{Browser, BrowserConfig};
use chromiumoxide::cdp::browser_protocol::network::{EventRequestWillBeSent, ResourceType};
use chromiumoxide::detection;
use futures::StreamExt;
use tokio::sync::Mutex;
use url::Url;

use crate::pathmap;

/// Maximum time to wait for a page to finish loading + JS execution.
const RENDER_TIMEOUT: Duration = Duration::from_secs(30);
/// Extra settle time after `networkidle` for lazy-loading / AJAX.
const SETTLE_DELAY: Duration = Duration::from_millis(1500);

/// A browser network request captured during rendering.
#[derive(Debug, Clone)]
pub struct CapturedResource {
    pub url: Url,
    pub resource_type: ResourceType,
}

/// Result of rendering one URL.
#[derive(Clone)]
pub struct RenderResult {
    /// Fully rendered HTML (post-JS execution) — what you'd see in DevTools.
    pub html: String,
    /// Static resources the browser requested while loading this page.
    pub resources: Vec<CapturedResource>,
    /// Internal navigation links (`<a href>`) found in the rendered DOM.
    pub links: Vec<Url>,
    /// Final URL after any redirects.
    pub final_url: Url,
}

/// Whether a CDP resource type should be downloaded for offline use.
pub fn is_static_resource_type(rt: &ResourceType) -> bool {
    matches!(
        rt,
        ResourceType::Document
            | ResourceType::Stylesheet
            | ResourceType::Script
            | ResourceType::Image
            | ResourceType::Font
            | ResourceType::Media
            | ResourceType::Manifest
    )
}

/// Whether a CDP resource type is a dynamic fetch (XHR, RSC, analytics, etc.).
pub fn is_dynamic_resource_type(rt: &ResourceType) -> bool {
    matches!(
        rt,
        ResourceType::Fetch
            | ResourceType::Xhr
            | ResourceType::EventSource
            | ResourceType::WebSocket
            | ResourceType::Other
    )
}

fn should_capture_resource(
    url: &Url,
    rt: &ResourceType,
    base_host: &str,
    base_port: Option<u16>,
) -> bool {
    if is_dynamic_resource_type(rt) {
        return false;
    }
    if !is_static_resource_type(rt) {
        return false;
    }
    if pathmap::is_dynamic_request(url) {
        return false;
    }
    if *rt == ResourceType::Document {
        return crate::crawler::is_same_domain(url, base_host);
    }
    pathmap::is_mirrorable_static(url, base_host, base_port)
}

/// Locate a Chromium/Chrome binary across all platforms.
fn find_browser() -> Result<PathBuf> {
    if let Ok(p) = std::env::var("CHROME") {
        let path = PathBuf::from(&p);
        if path.exists() {
            return Ok(path);
        }
        return Err(anyhow!("$CHROME points to '{p}' which does not exist"));
    }

    if let Ok(path) = detection::default_executable(detection::DetectionOptions::default()) {
        return Ok(path);
    }

    let candidates: &[&str] = &[
        "/usr/bin/google-chrome",
        "/usr/bin/google-chrome-stable",
        "/usr/bin/chromium",
        "/usr/bin/chromium-browser",
        "/snap/bin/chromium",
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    ];

    for c in candidates {
        if std::path::Path::new(c).exists() {
            return Ok(PathBuf::from(c));
        }
    }

    Err(anyhow!(
        "No Chrome/Chromium/Edge browser found.\n  \
         Install one, or set the CHROME environment variable to its path."
    ))
}

fn build_config(no_sandbox: bool) -> Result<BrowserConfig> {
    let exec = find_browser()?;
    let mut builder = BrowserConfig::builder()
        .chrome_executable(exec)
        .arg("--disable-gpu")
        .arg("--disable-dev-shm-usage")
        .arg("--disable-extensions")
        .arg("--disable-background-networking")
        .window_size(1280, 800);
    if no_sandbox {
        builder = builder.arg("--no-sandbox");
    }
    builder
        .build()
        .map_err(|e| anyhow!("Failed to build browser config: {e}"))
}

/// Launch a headless browser asynchronously.
pub async fn launch_browser_async(
    no_sandbox: bool,
) -> Result<(Browser, chromiumoxide::handler::Handler)> {
    let config = build_config(no_sandbox)?;
    Browser::launch(config)
        .await
        .map_err(|e| anyhow!("Failed to launch browser: {e}"))
}

/// Render a single URL: navigate, execute JS, capture HTML + typed network requests.
pub async fn render_page(
    browser: &Browser,
    url: &Url,
    base_host: &str,
    base_port: Option<u16>,
    wait_ms: u64,
) -> Result<RenderResult> {
    let page = browser
        .new_page("about:blank")
        .await
        .map_err(|e| anyhow!("Failed to open page: {e}"))?;

    let collected: Arc<Mutex<Vec<CapturedResource>>> = Arc::new(Mutex::new(Vec::new()));
    let seen: Arc<Mutex<HashSet<String>>> = Arc::new(Mutex::new(HashSet::new()));
    let collector = Arc::clone(&collected);
    let seen_collector = Arc::clone(&seen);
    let base_host_owned = base_host.to_string();
    let base_port_owned = base_port;

    let mut listener = page
        .event_listener::<EventRequestWillBeSent>()
        .await
        .map_err(|e| anyhow!("Failed to attach network listener: {e}"))?;

    let listener_handle = tokio::spawn(async move {
        while let Some(ev) = listener.next().await {
            let req_url = match Url::parse(&ev.request.url) {
                Ok(u) => u,
                Err(_) => continue,
            };
            let rt = match ev.r#type.clone() {
                Some(rt) => rt,
                None => continue,
            };
            if !should_capture_resource(&req_url, &rt, &base_host_owned, base_port_owned) {
                continue;
            }
            let mut no_frag = req_url.clone();
            no_frag.set_fragment(None);
            let key = no_frag.to_string();
            let mut guard = seen_collector.lock().await;
            if guard.insert(key) {
                collector.lock().await.push(CapturedResource {
                    url: no_frag,
                    resource_type: rt,
                });
            }
        }
    });

    let goto_result = tokio::time::timeout(RENDER_TIMEOUT, page.goto(url.as_str())).await;

    match goto_result {
        Ok(Ok(_)) => {}
        Ok(Err(e)) => {
            listener_handle.abort();
            let _ = page.close().await;
            return Err(anyhow!("Navigation failed for {url}: {e}"));
        }
        Err(_) => {
            listener_handle.abort();
            let _ = page.close().await;
            return Err(anyhow!("Timeout loading {url} after {:?}", RENDER_TIMEOUT));
        }
    }

    let settle = Duration::from_millis(wait_ms.max(SETTLE_DELAY.as_millis() as u64));
    tokio::time::sleep(settle).await;

    let mut prev_count = collected.lock().await.len();
    for _ in 0..20 {
        tokio::time::sleep(Duration::from_millis(500)).await;
        let cur = collected.lock().await.len();
        if cur == prev_count {
            break;
        }
        prev_count = cur;
    }

    let html = page
        .content()
        .await
        .map_err(|e| anyhow!("Failed to read page content: {e}"))?;

    let final_url = page
        .evaluate("window.location.href")
        .await
        .ok()
        .and_then(|v| v.into_value::<String>().ok())
        .and_then(|s| Url::parse(&s).ok())
        .unwrap_or_else(|| url.clone());

    listener_handle.abort();

    let mut resources = collected.lock().await.clone();
    {
        let mut seen_guard = seen.lock().await;
        merge_dom_resources(&page, base_host, base_port, &mut resources, &mut seen_guard).await;
    }

    let links = extract_links(&html, &final_url, base_host);
    let _ = page.close().await;

    Ok(RenderResult {
        html,
        resources,
        links,
        final_url,
    })
}

async fn merge_dom_resources(
    page: &chromiumoxide::Page,
    base_host: &str,
    base_port: Option<u16>,
    resources: &mut Vec<CapturedResource>,
    seen: &mut HashSet<String>,
) {
    let script = r#"
        () => {
            const urls = new Set();
            const add = (u) => { if (u) urls.add(u); };
            document.querySelectorAll('link[href]').forEach(el => add(el.href));
            document.querySelectorAll('script[src]').forEach(el => add(el.src));
            document.querySelectorAll('img[src]').forEach(el => add(el.src));
            document.querySelectorAll('source[src]').forEach(el => add(el.src));
            document.querySelectorAll('video[src]').forEach(el => add(el.src));
            document.querySelectorAll('audio[src]').forEach(el => add(el.src));
            return [...urls];
        }
    "#;

    if let Ok(eval) = page.evaluate(script).await {
        if let Ok(raw) = eval.into_value::<Vec<String>>() {
            for s in raw {
                if let Ok(mut u) = Url::parse(&s) {
                    u.set_fragment(None);
                    if pathmap::is_mirrorable_static(&u, base_host, base_port)
                        && !pathmap::is_dynamic_request(&u)
                        && seen.insert(u.to_string())
                    {
                        resources.push(CapturedResource {
                            url: u,
                            resource_type: ResourceType::Other,
                        });
                    }
                }
            }
        }
    }
}

fn extract_links(html: &str, base: &Url, base_host: &str) -> Vec<Url> {
    use scraper::{Html, Selector};

    let doc = Html::parse_document(html);
    let mut urls = Vec::new();

    let selectors = ["a[href]", "area[href]"];
    for sel_str in &selectors {
        if let Ok(sel) = Selector::parse(sel_str) {
            for elem in doc.select(&sel) {
                if let Some(href) = elem.value().attr("href") {
                    if let Some(abs) = crate::crawler::resolve_url(base, href) {
                        if crate::crawler::is_same_domain(&abs, base_host)
                            && !pathmap::is_dynamic_request(&abs)
                        {
                            urls.push(abs);
                        }
                    }
                }
            }
        }
    }

    urls
}

#[allow(dead_code)]
pub fn looks_like_spa(html: &str) -> bool {
    let lower = html.to_lowercase();

    let has_mount = lower.contains(r#"id="app""#)
        || lower.contains(r#"id='app'"#)
        || lower.contains(r#"id="root""#)
        || lower.contains(r#"id='root'"#)
        || lower.contains(r#"id="__nuxt""#)
        || lower.contains(r#"data-v-app"#);

    let has_script = lower.contains("<script");

    let text_len = strip_tags(&lower)
        .chars()
        .filter(|c| !c.is_whitespace())
        .count();

    has_mount && has_script && text_len < 200
}

fn strip_tags(html: &str) -> String {
    let mut out = String::with_capacity(html.len());
    let mut in_tag = false;
    for ch in html.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => out.push(ch),
            _ => {}
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_looks_like_spa_vue() {
        let html = r#"<!DOCTYPE html>
        <html><head><title>App</title></head>
        <body><div id="app"></div>
        <script src="/assets/index.abc123.js"></script>
        </body></html>"#;
        assert!(looks_like_spa(html));
    }

    #[test]
    fn test_static_types_include_font() {
        assert!(is_static_resource_type(&ResourceType::Font));
        assert!(is_dynamic_resource_type(&ResourceType::Fetch));
    }
}
